In [1]:
import pandas as pd

df1 = pd.read_csv("/content/dataset1.csv")
df2 = pd.read_csv("/content/dataset2.csv")

In [6]:
print(df1.columns)
print(df2.columns)

Index(['Temperature', 'Humidity', 'Rainfall', 'pH', 'N', 'P', 'K', 'Crop'], dtype='object')
Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [7]:
df1 = df1.rename(columns={
    "Temperature": "temperature",
    "Humidity": "humidity",
    "Rainfall": "rainfall",
    "pH": "ph",
    "Crop": "label"
})

In [8]:
columns = ["N","P","K","temperature","humidity","ph","rainfall","label"]

df1 = df1[columns]
df2 = df2[columns]

In [13]:
coffee_df = df2[df2["label"] == "coffee"]
coffee_df.shape

(100, 8)

In [30]:
merged_df = pd.concat([df1, coffee_df], ignore_index=True)
merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [31]:
merged_df["label"] = merged_df["label"].str.strip().str.title()

In [32]:
merged_df["label"].value_counts()

label
Coffee      40
Turmeric    15
Rubber      15
Ginger      15
Coconut     15
Paddy       15
Cardamom    15
Tapioca     15
Arecanut    15
Pepper      15
Banana      15
Name: count, dtype: int64

In [34]:
selected_crops = ["Coffee","Banana","Ginger","Pepper","Tapioca"]

merged_df = merged_df[merged_df["label"].isin(selected_crops)]
merged_df["label"].value_counts()

label
Coffee     40
Ginger     15
Tapioca    15
Pepper     15
Banana     15
Name: count, dtype: int64

In [35]:
merged_df.to_csv("final_soil_dataset.csv", index=False)

In [38]:
merged_df = merged_df.sort_values(by="label").reset_index(drop=True)
numeric_cols = ["N","P","K","temperature","humidity","ph","rainfall"]

merged_df[numeric_cols] = merged_df[numeric_cols].round(2)

In [39]:
merged_df.head()

     N   P    K  temperature  humidity    ph  rainfall   label
0  141  64  137        26.19     92.70  6.75   1699.74  Banana
1  148  77  149        29.51     74.47  7.22   2276.49  Banana
2  103  67  100        27.80     80.64  6.26   1577.72  Banana
3  138  60  145        28.80     79.38  6.22   2424.47  Banana
4  102  49  104        29.79     78.97  6.32   2078.95  Banana

In [40]:
merged_df.to_csv("soil_small_pre.csv", index=False)